[package]
name = "mandelbrot-explorer"
version = "1.0.4"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14" }
rayon = "1.11.0"
itertools = "0.14.0"


# Profile for profiling
[profile.profiling]
inherits = "release"
debug = true